package be.kdg.tic_tac_toe.model;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.TreeMap;

import static java.nio.file.StandardOpenOption.APPEND;

class PlayersSave {
    private static final Path players = Paths.get("resources" + File.separator + "saveFiles" + File.separator + "players.txt");

    private TreeMap<String, Integer> playersMap;
    private static final String template = """
            //\\\\PLAYERS FILE//\\\\
            //\\\\DO NOT EDIT THIS FILE MANUALLY//\\\\
            //\\\\THIS FILE IS AUTOMATICALLY GENERATED//\\\\
            //\\\\REMOVING LINES WILL CAUSE ERRORS EVEN BLANK LINES//\\\\
            //\\\\ANY CHANGE CAN CAUSE CORRUPTION OF YOUR SAVE FILE//\\\\
            //\\\\WHEN YOU EDIT THIS FILE, MAKE SURE YOU HAVE A BACKUP AND ALWAYS LEAVE ONE LINE EMPTY AT THE BOTTOM OF THIS FILE//\\\\
            ========================================================================================================================
            
            """;

    PlayersSave() throws SaveFileException {
        this.checkFile();
    }

    private void checkFile() throws SaveFileException {
        if (!Files.exists(players)) {
            try {
                Files.createFile(players);
                System.out.println("File created: " + players.getFileName());
            } catch (IOException e) {
                throw new SaveFileException("File could not be created: " + players.getFileName());
            }
        } else {
            System.out.println("File already exists: " + players.getFileName());
        }
    }

    void writePlayers(String playerName1, String playerName2, boolean human) throws SaveFileException {
        boolean name1 = false;
        boolean name2 = false;
        //create the scanner
        try (Scanner scanner = new Scanner(players)) {
            //loop through the file
            while (scanner.hasNextLine()) {
                //read the line
                String line = scanner.nextLine();
                //check if the line contains the player and score
                if (line.contains("player") && line.contains("score")) {
                    //check if the name is already in the file
                    if (checkName(line, playerName1, human)) {
                        name1 = true;
                    } else if (checkName(line, playerName2, human)) {
                        name2 = true;
                    }
                }
            }
            //if the name is not in the file, add it
            if (!name1) {
                Files.write(players, String.format("player:%s;score:0%n", playerName1).getBytes(), APPEND);
            }
            if (!name2 && human) {
                Files.write(players, String.format("player:%s;score:0%n", playerName2).getBytes(), APPEND);
            }

            this.fillList();
        } catch (IOException e) {
            throw new SaveFileException("File could not be written: " + players.getFileName());
        }
    }

    private boolean checkName(String line, String name, boolean human) {
        return line.split(";")[0].split(":")[1].replace(" ", "").equalsIgnoreCase(name.replace(" ", "")) && human;
    }

    private void fillList() throws SaveFileException {
        try (Scanner scanner = new Scanner(players)) {
            //loop through the file
            while (scanner.hasNextLine()) {
                //read the line
                String line = scanner.nextLine();
                //check if the line contains the player and score
                if (line.contains("player") && line.contains("score")) {
                    String name = this.getPlayer(line);
                    int score = this.getScore(line);

                    playersMap.put(name, score);
                }
            }
        } catch (IOException e) {
            throw new SaveFileException("An Error occurred in: " + players.getFileName());
        }
    }

    void updateScore(boolean draw, Player winner, Contribution contribution) {
        int score = 0;
        if (draw) {
            score = 1;
        } else {
            if (contribution.getPlayer(2) instanceof NPC && winner instanceof Human) {
                score = 3;
            } else if (contribution.getPlayer(2) instanceof Human) {
                score = 2;
            }
        }

        try (Scanner scanner = new Scanner(players)) {
            //loop through the file
            while (scanner.hasNextLine()) {
                //read the line
                String line = scanner.nextLine();

                //check if the line contains the player and score
                if (line.contains("player") && line.contains("score")) {
                    this.addScore(this.getPlayer(line), this.getScore(line));
                }
            }
//TODO find best way to save names and to write names
        } catch (IOException e) {

        }
    }

    private void addScore(String player, int score) {
        int pscore = playersMap.get(player);
        pscore += score;
        playersMap.put(player, pscore);
    }

    private String getPlayer(String line) {
        return line.split(";")[0].split(":")[1];
    }

    private int getScore(String line) {
        return Integer.parseInt(line.split(";")[1].split(":")[1]);
    }


}
